### ISSUE TITLE
predict.bru, new data set

### ISSUE THREAD

**Issue by bachlaw** [fbachl/inlabru#105]
Having some trouble getting `predict.bru` to work making predictions on (1) a new set of data, preferably also accommodating new random effects levels like INLA does with normal predictions, (2) marginalizing out one or more random effects for each prediction. 

Example:

```
set.seed(1234)
fit.data <- tibble(b1 = sample(c(1,0), 2e3, replace=TRUE),
                   b2 = rnorm(2e3, 0, 1),
                   z1 = sample.int(c(100), 2e3, replace=TRUE),
                   z2 = sample.int(c(200), 2e3, replace=TRUE),
                   y = rbinom(2e3, prob=.7, size=1))

pred.data <- tibble(b1 = sample(c(1,0), 2e3, replace=TRUE),
                    b2 = rnorm(2e3, 0, 1),
                    z1 = sample.int(c(120), 2e3, replace=TRUE),
                    z2 = sample.int(c(220), 2e3, replace=TRUE),
                    y = NA)
                    
bru.fit <- bru(y ~ Intercept(1) + b1 + b2 + z1(z1, model="iid", initial=4) + z2(z2, model="iid", initial=4), data=fit.data, family="binomial", options = bru_options(verbose=TRUE, control.inla=list(int.strategy = "eb")))
                    
preds.fit <- predict(bru.fit)
preds.new <- predict(bru.fit, data=pred.data)
```
When I try to use `predict.bru`, I am getting stuck.

My questions:

(1) For both predictions above, I am getting 14 rows in the predictor slot.  Why would this be?  I was expecting a full 2,000 predictions, one for each row.  The predictions in the predictor slot do appear to be different in each set, so that is certainly a good start.

(2) I am struggling a bit with getting the formula specified, as indicated by the simplicity of the predictions being made above.  
I would like to do separate predictions on brand new data like `~Intercept + b1 + b2 + z1` and `~Intercept + b1 + b2 + z2`.  The only thing I care about is the full set of predictions off the data set in question, whether it is the original model data or a set of new data.  (Essentially, this is like using `re.form` in `lme4` or the Stan front ends.  Put still another way, I essentially am looking to get outputs similar to if I applied each of these marginalizations to the data itself, changed the outcome to NA, and tacked them on to the original data set during fitting, but preferably without that computational burden.  Do you have suggestions on how these results could be achieved with `predict.bru`?

I have managed to get some Intercept and fixed effect predictions back by adding `_latent` to the end.  But that only gets me a row for each variable in the formula, not the fresh set of 2,000 predictions based solely off those variables.  It also doesn't seem to work the same way for random effects.  I unfortunately seem to be missing something.

Thanks again for a very useful package and especially for all the work being done on it as of late. The ability to make predictions onto new data using sampling is a wonderful capability.

**Comment by ASeatonSpatial** [comment]
The code above doesn't run, I think you meant to put a different formula in the call to bru?

**Comment by bachlaw** [comment]
> The code above doesn't run, I think you meant to put a different formula in the call to bru?

Weird.  Let me check it and update as appropriate.  I apologize for the inconvenience.

**Comment by finnlindgren** [comment]
I've edited it now to add a + before b1. But you also don't have a definition of z1 and z2. Why that doesn't give an error or warning is a possible bug, but is also related to backwards compatibility issues. Below I assume you meant `z1(b,..)` and `z2(c,...)`, but "c" is a dangerous variable name as it clashes with the c() function.

The predict calls here actually ignore the data argument (which should really be "newdata" to match other predict() methods; at some point I'll change that and add a warning about the data argumrnt) since without an explicit expression to calculate, ti will do separate prediction for each model component; essentially just a summary of samples of each component.

To predict a specific expression, you need to supply `formula = ~ expression`, even if that's just the basic linear predictor using all the model components.

For predictions that include "iid" random effects models evaluated for new indices, you can use `rnorm` explicitly, referencing the precision parameter to specify the standard deviation; there is currently no method for doing this automatically. You can find the names of the paramters by looking at the summary() output and replacing all sequences of special characters with an underscore, _. (At some point that information will be made more easily available, and also available via a component suffix _param or similar, like the _latent feature)

Example, assuming all the prediction data should use new realisations of the random effect z1:
```
preds.new <- predict(
  bru.fit,
  data = pred.data,
  formula = ~ Intercept + rnorm(max(b), sd = Precision_for_z1^-0.5)[b]
)
```

**Comment by finnlindgren** [comment]
Further to your second question, you can do multiple predictions by having the prediciton expression generate a data.frame. Each column will generate a separate prediction output, as a named list. Example:
```
preds.new <- predict(
  bru.fit,
  data = pred.data,
  formula = ~ data.frame(
    Z1 = Intercept + b1 + b2 +
      rnorm(max(b), sd = Precision_for_z1^-0.5)[b],
    Z2 = Intercept + b1 + b2 +
      rnorm(max(c), sd = Precision_for_z2^-0.5)[c]
  )
)
```

**Comment by finnlindgren** [comment]
What these iid random effect predictions do _not_ do is to detect if one of the b- or c-values were also in the estimation set.
For that, you need to combine `z1` values with `rnorm`-values, depending on the value of b, for each element of the `b`-vector in the prediction data. "Straightforward but tedious" to write such code, I suspect, but the nice thing is that it can be encapsulated in a separate function that you call inside the prediction expression. If this becomes directly supported in the future, that's likely how such a feature would work.

**Comment by finnlindgren** [comment]
And note that in these examples, it's actually a good thing to have the input variables have a different name than the model component, since in the prediction expression, and model formula itself, the component names refer to the _effect_ of the component, and not the values of the inputs.

**Comment by finnlindgren** [comment]
Complete example:
```
library(tidyverse)
library(inlabru)

set.seed(1234)
fit.data <- tibble(b1 = sample(c(1,0), 2e3, replace=TRUE),
                   b2 = rnorm(2e3, 0, 1),
                   b = sample.int(c(100), 2e3, replace=TRUE),
                   c = sample.int(c(200), 2e3, replace=TRUE),
                   y = rbinom(2e3, prob=.7, size=1))

pred.data <- tibble(b1 = sample(c(1,0), 2e3, replace=TRUE),
                    b2 = rnorm(2e3, 0, 1),
                    b = sample.int(c(120), 2e3, replace=TRUE),
                    c = sample.int(c(220), 2e3, replace=TRUE),
                    y = NA)

bru.fit <- bru(y ~ Intercept(1) + b1 + b2 + z1(b, model="iid", initial=4) +
                 z2(c, model="iid", initial=4),
               data=fit.data, family="binomial",
               options = bru_options(verbose=TRUE,
                                     control.inla=list(int.strategy = "eb")))

# Predict the individual components:
preds.fit <- predict(bru.fit)
# Incorporate new random effect values
preds.new <- predict(
  bru.fit,
  data = pred.data,
  formula = ~ Intercept + rnorm(max(b),
                                sd = Precision_for_z1^-0.5)[b]
)
#Multiple predictions:
preds.new <- predict(
  bru.fit,
  data = pred.data,
  formula = ~ data.frame(
    Z1 = Intercept + b1 + b2 +
      rnorm(max(b), sd = Precision_for_z1^-0.5)[b],
    Z2 = Intercept + b1 + b2 +
      rnorm(max(c), sd = Precision_for_z2^-0.5)[c]
  )
)
```

**Comment by finnlindgren** [comment]
Currently, the easiest way to do prediction both for iid effects from the estimation itself, and for new values, is to use separate formulas; one using just `+ z1` or `+z2`, and one using the `rnorm` construction.

**Comment by finnlindgren** [comment]
There are cases where unexpected things will happen due to the internal structure of the calculations, e.g. not warning about values that should really be undefined. There can be hard to detect unfortunately, so one needs to be careful when specifying the expressions. For example, it won't complain about using `+z1` even though the prediction `b` values go beyond the maximum index available for the model. This can be fixed for "iid" and some other models, but for most models some kind of constant extrapolation will happen.

**Comment by bachlaw** [comment]
Wonderful: thanks very much for this.  I will work through these examples and see if they do the trick.  

> preds.new <- predict(
>   bru.fit,
>   data = pred.data,
>   formula = ~ data.frame(
>     Z1 = Intercept + b1 + b2 +
>       rnorm(max(b), sd = Precision_for_z1^-0.5)[b],
>     Z2 = Intercept + b1 + b2 +
>       rnorm(max(c), sd = Precision_for_z1^-0.5)[c]
>   )
> )

Finn, for the `z2` predictions here, would I use the precision for `z2` instead of `z1`?

This is helpful because one of my issues was getting `z1` or `z2`  f/k/a `b` and `c` to be recognized by the formula expression when predicting.  By the way, what is the rationale for using `max` for the random effect mean value? Is it just a manner of selecting one of the values which presumably should be the same on average?

**Comment by bachlaw** [comment]
I also suspect some clever `ifelse` type logic can deal with the issue of the newly-observed level.  I will give that some thought and post if I find something that works well enough.

**Comment by finnlindgren** [comment]
Yes, I've now edited my examples to use the correct precision parameters.

The `max(b)` is for the number of samples (not for the mean value) so that it will simulate at least as many values as the indices. Then the `[b]` indexing will extract the correct value for each data row; This is needed when the same effect value is involved in different rows.  The mean value of the iid model is zero, which is the default value for `mean` in `rnorm`, so I didn't specify it.

**Comment by finnlindgren** [comment]
My examples assume that b- and c-values should generate new random numbers from the model, and ignores that the same indices may have been involved in the estimation data. Hence the need for something that merges the two kinds of predictions when that's not the correct behaviour.

**Comment by bachlaw** [comment]
The fine folks behind `lme4` deal with new levels seamlessly through `allow.new.levels=TRUE` on their `predict` function so perhaps they have some code that can be borrowed also. We'll figure something out.

**Comment by finnlindgren** [comment]
The internals are likely to be extremely different unfortunately. inlabru relies on INLA itself to generate samples from the models, and the size of each latent model there is a very fixed value (the inbuilt predictions in "plain" INLA are made by explicitly making the model larger to include both the estimation values and the predictions in a joint model). The iid model is only special in that it's obvious in principle how to extend it to new indices. Very few models have that property. But this also means that implementing a special feature that works just for the iid model probably would be ok.

**Comment by finnlindgren** [comment]
The new `_eval` feature may be the best place to implement this; internally, that defines a local function for each model component, that evaluates it for arbitrary values. For iid, this could be a special function that samples new values for input indices not in the estimated model. With that extension, one could use `+z1_eval(b, prec = Precision_for_z1)` in the `predict()` call, and the `ifelse` logic and `rnorm` call hidden away inside the internal evaluator function.

This would still not cover all situations though, e.g. for all models, one can have `replicate=` create independent copies. These would be _much_ harder to generate new values for, since they would involve arbitrary main models.

**Comment by bachlaw** [comment]
I agree. `iid` is the baseline workhorse so offering a solution for that and not others is completely justified, especially at first.

**Comment by finnlindgren** [comment]
In 47eea0a I've implemented a basic version of this for "iid" models. It currently requires `mapper = bru_mapper_index(n)` to be explicitly specified in the model component, as the default mapper method is different and would require more work to allow this. See the test at the end of https://github.com/inlabru-org/inlabru/blob/devel/tests/testthat/test_predict.R for an example that generates posterior samples for an iid component with some indices in the estimated model, and some freshly generated based on the (posterior sample of) precision parameter for the iid model.
An extra complication I had to handle was that if the _eval function is called twice in the same expression, or if the same index appears twice in the input, it needs to reuse the simulated new values. This is handled by a cache system, that is cleared at the start of each predictor evaluation.

The basic use in prediction formulas for an iid component called `name` is `name_eval(indices)`. The precision parameter is automatically extracted internally, from `Precision_for_name`.

I've added basic testing, but we need to test that it indeed generates values with the correct distribution before proper use of this feature!

**Comment by finnlindgren** [comment]
In 47eea0a I've implemented a basic version of this for "iid" models. It currently requires `mapper = bru_mapper_index(n)` to be explicitly specified in the model component, as the default mapper method is different and would require more work to allow this. See the test at the end of https://github.com/inlabru-org/inlabru/blob/devel/tests/testthat/test_predict.R for an example that generates posterior samples for an iid component with some indices in the estimated model, and some freshly generated based on the (posterior sample of) precision parameter for the iid model.
An extra complication I had to handle was that if the _eval function is called twice in the same expression, or if the same index appears twice in the input, it needs to reuse the simulated new values. This is handled by a cache system, that is cleared at the start of each predictor evaluation.

The basic use in prediction formulas for an iid component called `name` is `name_eval(indices)`. The precision parameter is automatically extracted internally, from `Precision_for_name`.

I've added basic testing, including a check that the variance of the newly generated variables matches the variance implied by the estimated precision parameter.
