### ISSUE TITLE
Incorrect namespace in `gg.fm_mesh_2d`

### ISSUE THREAD

**Issue by simon-smart88** [fbachl/inlabru#250]
Here: https://github.com/inlabru-org/inlabru/blob/302fee38d8a8b5c644ca48b7fb045f2b7dff66fd/R/ggplot.R#L801 

There don't seem to be any INLA functions used in the function, but there are several fmesher ones, so I believe that it should be:

`requireNamespace("fmesher")`

**Comment by finnlindgren** [comment]
Good catch! That was a leftover from before fmesher was split off into its own package. I found a few more such instances, as well as updated several documentation mentions of `inla.mesh` and `inla.mesh.1d` to the new `fm_mesh_2d` and `fm_mesh_1d` classes.  The code doesn't need an explicit `requireNamespace("fmesher")` since `inlabru` `Depends` on `fmesher`.
