### ISSUE TITLE
mexdolphins data: polygon seems incorrect

### ISSUE THREAD

**Issue by dill** [fbachl/inlabru#53]
The polygon in `mexdolphin$ppoly` seems wrong to me.

In `dsm` the polygon has 45 vertices. In `inlabru` it has 158. This in itself is of course not really an issue, but the polygon vertices seem to loop back on themselves. Perhaps it's easier to show this in graphics/code:

```r
data(mexdolphin, package="inlabru")
# avoid sp stuff...
poly <- mexdolphin$ppoly@polygons[[1]]@Polygons[[1]]@coords

plot(poly[1:79,], type="l", asp=1)

```

![screen shot 2018-11-20 at 14 45 51](https://user-images.githubusercontent.com/1953/48780996-fefbc400-ecd2-11e8-8170-85127a44dc91.png)

Okay, fine, then we can append the first vertex as the last and make a polygon, but what about the other 79 points?

```r
plot(poly[80:158,], type="l", asp=1)
```

![screen shot 2018-11-20 at 14 47 18](https://user-images.githubusercontent.com/1953/48781090-323e5300-ecd3-11e8-8844-0c51e9265832.png)

We get almost *but not quite* the same thing again. Plotting everyting and zooming-in, we see there is a weird overlap:

```r
plot(poly, type="l", asp=1, xlim=c(-50,0), ylim=c(-1500, -1450))
```

![screen shot 2018-11-20 at 14 48 59](https://user-images.githubusercontent.com/1953/48781186-6dd91d00-ecd3-11e8-86b4-c24bd947b75d.png)

Apologies if there is some INLA-y reason that you do this (if there is I'm keen to know!), it's caused havoc for me doing point-in-polygon using `mgcv::inSide` this afternoon.

**Comment by finnlindgren** [comment]
Looks like the whole polygon is duplicated? I have a non functioning laptop at the moment. Can you plot the x and y coordinates a sfunctions of index, so one can see if the loops go the same direction or if the duplicate is in the opposite direction? I’m not sure where the poly data originated.

**Comment by dill** [comment]
Well I think they might have come from me originally... but I don't know how they went from the 45 vertex versions to these... Perhaps something strange happened during projection? (Version in `dsm` is in lat/long.)

As requested:

```r
par(mfrow=c(1,2))
plot(poly[,1], ylab="x")
plot(poly[,2], ylab="y")
```

![screen shot 2018-11-20 at 15 09 23](https://user-images.githubusercontent.com/1953/48782603-7848e600-ecd6-11e8-9b6d-88e90b7cc6e9.png)

**Comment by finnlindgren** [comment]
It appears that the code that converted the data from dam is here: 
https://github.com/cran/inlabru/blob/master/R/data.mexdolphin.R
Unfortunately it can’t be run anymore due to a removed function, but the code might reveal the source of the problem. In any case, it’s clear that the polygon info is wrong!

**Comment by finnlindgren** [comment]
This is the culprit:
`polyloc = as.data.frame(mexdolphin$mesh$loc[mexdolphin$mesh$segm$int$idx,c(1,2)])`
It assumed incorrectly that segm$int$idx would be a vector, but it’s normally a two-column matrix. The increase from 45 to 79 was due to the dsm polygon being used as input to the mesh refinement, and then extracted from the resulting mesh.

**Comment by dill** [comment]
Aha! Okay, I was going to volunteer to fix this but given that the 
function is missing I'll shy away from that task...
