### ISSUE TITLE
Is pardiso supported?

### ISSUE THREAD

**Issue by ghost** [fbachl/inlabru#72]
When running inlabru on the Linux based HPC, I was wondering if pardiso is utilized, and if so, have I activated this in the correct way? 

e.g.

INLA:::inla.dynload.workaround() ## Our HPC is running an older version of GLIBC

bru.options(pardiso.license = "Licenses/pardiso.lic")
inla.setOption(pardiso.license = "Licenses/pardiso.lic") # Is this line necessary?

inla.pardiso.check()
[1] "SUCCESS: PARDISO IS INSTALLED AND WORKING"

inlabru:::lgcp(............)

Cheers,

Harri

**Comment by finnlindgren** [comment]
All pardiso related things are handled internally in the INLA package, so it should work the same with inlabru. Since inlabru doesn't know anything directly about it, you need to use the inla package options, either globally, or with the feed-through mechanism from inlabru. If the only step you would use to activate pardiso in plain INLA is
```
inla.setOption(pardiso.license = "Licenses/pardiso.lic")
```
then that's all that should be needed to use it with inlabru.
